### PR TITLE
Allow experimental argument

### PR DESCRIPTION
**Pull request by aleixrodri98**
Allow to pass the experimental argument, very useful for line identing

Link here: https://github.com/hhatto/autopep8/issues/180

### CODE REVIEW

**Comment by wistful** [comment]
The option was deliberately removed in 9ff73acc3e88cccebb27ac56c5de93d6c1d8a78d.
No plans of returning it back anytime soon.

**Comment by wistful** [comment]
Could you provide useful cases of using --experimental option?

**Comment by aleixrodri98** [comment]
Yes, as I added before: Link here: https://github.com/hhatto/autopep8/issues/180

**Comment by wistful** [comment]
The 'experimental' option looks good.
Please remove 'agressive' option from the changes.

**Pull request closed without merging**
